### ISSUE TITLE
slayerSNN can not available

### ISSUE THREAD

**Issue by GitHubmalajava** [clear-nus/VT_SNN#10]
I have run the order: python setup.py install. it's success. But import slayerSNN as snn has error. slayerSNN can not available._

**Comment by tasbolat1** [comment]
@GitHubmalajava ,
Please provide more details so that we can help to solve the issue. In mean time if you've gotten that error, it means you haven't installed the SLAYER properly. Please follow installation instruction at [SLAYER ](https://github.com/tasbolat1/slayerPytorch/tree/856e0107447f5134766639cc14a095acdf030b4f). Please, also run unittest as it helps to debug.

**Comment by GitHubmalajava** [comment]
@tasbolat1 ,
 I ran unittest, but it got an error, showing that the problem was a scalar type error, runtimeError: Expected scalar type Float but found Double. Maybe my Slayer has a problem, but the command I ran: python setup.py install, the downloaded SNN package is in the package of my other Anaconda environment and not in the 'src' under the Slayer directory

**Comment by tasbolat1** [comment]
@GitHubmalajava can you explain what do you mean by another environment? are you running your `python setup.py install` under same environment where you run unittest? If so, can you also show what is the output of your installation log?

**Comment by GitHubmalajava** [comment]
@tasbolat1 ，
I used the virtual environment in the directory before, and then I reinstalled the Anaconda runtime environment. The previous problem was solved, but there are still problems: File "F:\VT_SNN-master\slayerPytorch\test\test_slayer011.py", line 35, in

pspGT = slayer.psp(spikeIn)

File "D:\Anaconda3\envs\VTSNN\lib\site-packages\slayersnn-0.0.0-py3.9.egg\ slayersnn \slayer. Py ", line 142, in PSP

return _pspFunction.apply(spike, self.srmKernel, self.simulation['Ts'])

File "D:\Anaconda3\envs\VTSNN\lib\site-packages\slayersnn-0.0.0-py3.9.egg\ slayersnn \slayer.py", line 672, in forward

psp = slayerCuda.conv(spike.contiguous(), filter, Ts)

RuntimeError: expected scalar type Float but found Double

**Comment by GitHubmalajava** [comment]
@tasbolat1 ，
It should be another problem, I still need to modify some code

**Comment by GitHubmalajava** [comment]
@tasbolat1 ，
When I run the command: python-m unittest there are still errors, I use the anaconda environment of py36. Traceback (most recent call last):

File "D:\Anaconda3\envs\VTS\lib\unittest\loader.py", line 428, in _find_test_path

module = self._get_module_from_name(name)

File "D:\Anaconda3\envs\VTS\lib\unittest\loader.py", line 369, in _get_module_from_name

__import__(name)

File "F:\VT_SNN-master\slayerPytorch\test\test_slayer012.py", line 41, in
pspGT = slayer.psp(spikeIn)
File "D:\Anaconda3\envs\VTS\lib\site-packages\slayersnn-0.0.0-py3.6.egg\ slayersnn \slayer. Py ", line 142, in PSP
return _pspFunction.apply(spike, self.srmKernel, self.simulation['Ts'])
File "D:\Anaconda3\envs\VTS\lib\site-packages\slayersnn-0.0.0-py3.6.egg\ slayersnn \slayer.py", line 672, in forward
psp = slayerCuda.conv(spike.contiguous(), filter, Ts)

RuntimeError: expected scalar type Float but found Double

I'm still confused. Can you give me some advice。ThankYou

**Comment by tasbolat1** [comment]
@GitHubmalajava ,
I recommend you to open issue on [SLAYER's](https://github.com/bamsumit/slayerPytorch/issues) github page. I believe SLAYER authors can help on this issue. 

In mean time check your pyTorch version. We are using 1.4.0 and it is tested with Python 3.6.10.

**Comment by GitHubmalajava** [comment]
@tasbolat1 ，
OK, thank you very much

**Comment by tasbolat1** [comment]
@GitHubmalajava 
I will leave this thread open, please update once you resolve the issue.

**Comment by tasbolat1** [comment]
issue is resolved at https://github.com/bamsumit/slayerPytorch/issues/64
closing
