### ISSUE TITLE
joint layer

### ISSUE THREAD

**Issue by GitHubmalajava** [clear-nus/VT_SNN#12]
@tasbolat1 ,
Hi,I would like to know how the visual and tactile joint layer is designed in this paper, or how the output size of visual SNN and tactile SNN are considered when reaching the joint layer
How does the visual SNN and tactile SNN data fuse into the joint layer

**Comment by tasbolat1** [comment]
Hi @GitHubmalajava ,
Thanks for interest on our work. Please, have a look at subsection _Model Architecture_ within section IV. We used 50 and 10 for output layers of tactile and vision SNNs respectively. These numbers are just hyper parameters we tuned to improve accuracy.
For combination layer, we concatenated features from tactile and vision SNNs to feed classification SNN. There are other couple of ways one can do with combination layer, but concatenation worked good for us.
I hope this answers your question. Feel free to ask more if needed.

**Comment by GitHubmalajava** [comment]
@tasbolat1 ,
Okay, thank you for your answer，I'm wondering if the visual SNN doesn't play a good role in the overall VT--SNN?
Is the visual event data used essentially for object weight classification not very useful。I would like to improve a good method on object weight classification.
Looking forward to your reply。

**Comment by tasbolat1** [comment]
Hi @GitHubmalajava ,

I think author of TactileSGNet explained the reason for using for difference [here](https://github.com/clear-nus/TactileSGNet/issues/7#issuecomment-1191254202)

For your question, yes you can combine them to run your experiments, there is nothing wrong with it. However, you need to adjust the layers for it.

**Comment by GitHubmalajava** [comment]
@tasbolat1 
OK, thank you very much.

**Comment by tasbolat1** [comment]
@GitHubmalajava ,

Alright, hopefully it helps. I am closing this issue for now, please feel free to re-open if you have more questions.
