### ISSUE TITLE
RuntimeError: CUDA error: invalid device function

### ISSUE THREAD

**Issue by superggb** [clear-nus/VT_SNN#6]
I created a py3.6 env and installed this project following instructions.But when I ran the train_snn.py . It came up with this error:
`Traceback (most recent call last):
  File "vtsnn/train_snn.py", line 219, in <module>
    _train()
  File "vtsnn/train_snn.py", line 181, in _train
    correct += torch.sum(snn.predict.getClass(output) == label).data.item()
  File "/home/anaconda3/envs/vtsnn/lib/python3.6/site-packages/slayerSNN-0.0.0-py3.6.egg/slayerSNN/spikeClassifier.py", line 19, in getClass
    numSpikes = torch.sum(spike, 4, keepdim=True).cpu()
RuntimeError: CUDA error: invalid device function
train_snn.sh: line 11:  8592 Segmentation fault      (core dumped) python vtsnn/train_snn.py --epochs 500 --lr 0.001 --sample_file 1 --batch_size 8 --network_config network_config/slip_detection.yml --data_dir slip_preprocessed --hidden_size 32 --loss NumSpikes --mode tact --task slip
`
I tried other torch version but none of them worked. I am sure torch and cuda can run well in other code. So what's the problem?
BTW:
my envs are : py3.6   cuda10.0    gpu2080ti

**Comment by jethrokuan** [comment]
@superggb did you figure out what the issue was?

**Comment by superggb** [comment]
Yes. It's a problem with slayer. When I setup slayer correctly, it's solved.
